language: node_js
node_js:
- "5"
branches:
  only:
  - source-code
before_install:
- npm install -g hexo
- npm i hexo-generator-json-content -g
install:
- npm install
before_script:
- git config --global user.name 'Indra Kusuma via Travis CI'
- git config --global user.email 'indrakusuma.udinus@gmail.com'
script:
- hexo clean
- hexo generate
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mkdir .deploy; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd .deploy; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git init; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git remote add origin $DEPLOY_REPO; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cp -r ../public/* .; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ls .; fig
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git add * .; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git commit -m 'Site updated'; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push --force --quiet origin master; fi

# - mkdir .deploy
# - cd .deploy
# - git init
# - git remote add origin $DEPLOY_REPO
# - cp -r ../public/* .
# - git add -A .
# - git commit -m 'Site updated'
# - git push --force --quiet origin master
