/*
 * Generated by scripts/generate-logo.mjs from assets/logo-source.png — do not edit.
 *
 * Inlined rather than served as an <img> so the ink tokens in globals.css apply: an
 * <img> is its own document and cannot see [data-theme] on <html>, which would leave
 * the mark stuck on the OS colour scheme whenever it disagrees with the site toggle.
 */
export default function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 587 590"
      role="img"
      aria-label="Indra Kusuma"
      xmlns="http://www.w3.org/2000/svg"
    >
      <defs>
        <linearGradient id="ik-logo-red-0" gradientUnits="userSpaceOnUse" x1="264" y1="380" x2="541" y2="569">
          <stop offset="0" stop-color="#d30233"/>
          <stop offset="1" stop-color="#fe7c7f"/>
        </linearGradient>
        <linearGradient id="ik-logo-red-1" gradientUnits="userSpaceOnUse" x1="6" y1="142" x2="200" y2="16">
          <stop offset="0" stop-color="#f6023e"/>
          <stop offset="1" stop-color="#fe797d"/>
        </linearGradient>
        <linearGradient id="ik-logo-ink-2" gradientUnits="userSpaceOnUse" x1="16" y1="545" x2="163" y2="258">
          <stop offset="0" stop-color="var(--logo-ink)"/>
          <stop offset="1" stop-color="var(--logo-ink)"/>
        </linearGradient>
        <linearGradient id="ik-logo-ink-3" gradientUnits="userSpaceOnUse" x1="251" y1="353" x2="475" y2="49">
          <stop offset="0" stop-color="var(--logo-ink-shade)"/>
          <stop offset="1" stop-color="var(--logo-ink)"/>
        </linearGradient>
      </defs>
      <path fill="url(#ik-logo-red-0)" d="M325 289L587 589Q378.8 609.6 351.5 533.5Q295.6 467.2 282 454Q252.4 424.4 252.5 415.5Q243.6 401.2 245.5 390.5Q244.2 376.6 246.5 373.5Q247 368.6 252 361Q243.8 364.2 290.5 321.5L325 289Z" />
      <path fill="url(#ik-logo-red-1)" d="M173.5 0L218 0Q217.4 36.8 207.5 52Q201 70.2 190 78.5Q181 89.8 167.5 97.5Q181 95 77.5 142L0 178Q-0.4 117.4 1 117.5Q0.6 112.8 6.5 95.5Q10.4 79.4 17 70.5Q20 61.6 36.5 45.5Q51.6 27.8 59.5 24.5Q66 18.2 86 11Q104.6 2 116 2Q116.4 -0.8 173.5 0Z" />
      <path fill="url(#ik-logo-ink-2)" d="M165 137L166 137Q166.8 628.2 164 557Q164 564.8 155 573.5Q149.2 583.8 138 586Q149.6 591.6 64 590L0 590Q-0.6 162.6 1.5 226.5Q1.8 221.6 7.5 214Q11.8 205.8 17 203Q-4.4 209.8 93 168Q192 124.6 165 137Z" />
      <path fill="url(#ik-logo-ink-3)" d="M516.5 46Q578.6 45.6 570.5 47L578 48Q345.6 272.4 311 303Q235.6 371.6 252 361Q247 368.6 246.5 373.5Q244.4 377.6 245 388Q244.2 397.8 247 404Q248.8 412.2 251.5 415L254 419L253 421Q176.4 333.4 184.5 340Q180.6 335 178.5 325.5Q175 317.2 176 308Q174.2 300.2 180.5 287Q178.8 278.6 205 254Q194.6 261.8 321 140Q444.8 10 443.5 46.5Q462 45.8 516.5 46Z" />
    </svg>
  );
}
